spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: Algmis-mysql
    url: jdbc:mysql://localhost/robot_approve
    username: lch
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
mybatis:
  mapper-locations: classpath*:sqlmap/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'